### ISSUE TITLE
License is not machine readable

### ISSUE THREAD

**Issue by chrysn** [GlobalPlatform/TPS-API-Reference-Implementations#14]
The license (of tps_minicbor,  didn't check the other crates) is well-defined, but hard to consume: A human reader may recognize it visually as MIT license but will still need to do a copy-paste verification that it's the same license (and yes people should do this, I've seen copies of MIT-style licenses with added clauses that were easy to miss), and it's hard to machine process.

If the license is identical to the [SPDX MIT license](https://spdx.org/licenses/MIT.html), please consider setting it in Cargo.toml as `license = "MIT"`. This will allow downstream users to mark it as good automatically (eg. when using `cargo deny`), and it won't show as "non-standard" license any more on https://crates.io/crates/tps_minicbor.

**Comment by quic-jodonogh** [comment]
License is SPDX MIT. I will make the changes in the manifests for each of the sub-projects. I will have to leave the LICENSE.txt in place as it is required by my employer (who pays me for at least some of the time I spend on this).

May take me a couple of days to get to it.
